In [20]:
import pandas as pd
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense

In [21]:
data=pd.read_csv("/content/Original Data.csv")

In [22]:
data

,student_id,skills,experience_years,course_grades,projects_completed,extracurriculars,job_offer
0,1,Python;Data Analysis;SQL,3,75.26,9,0,1
1,2,Java,4,74.25,6,2,1
2,3,Data Analysis,2,74.89,4,3,0
3,4,Data Analysis,4,72.73,2,3,1
4,5,Machine Learning;Python;C++,4,84.85,1,4,0
...,...,...,...,...,...,...,...
19995,19996,Python,1,62.54,1,2,1
19996,19997,Python;Machine Learning,2,84.13,2,2,1
19997,19998,Data Analysis;Java;Machine Learning,1,83.76,7,2,1
19998,19999,SQL;Python,2,60.50,2,3,1
19999,20000,Machine Learning,1,73.69,9,3,1

In [23]:
data.columns

Index(['student_id', 'skills', 'experience_years', 'course_grades',
       'projects_completed', 'extracurriculars', 'job_offer'],
      dtype='object')

In [24]:
x=data[['student_id', 'skills', 'experience_years', 'course_grades',
       'projects_completed', 'extracurriculars']]

In [25]:
x.size

120000

In [26]:
x.shape

(20000, 6)

In [27]:
x

,student_id,skills,experience_years,course_grades,projects_completed,extracurriculars
0,1,Python;Data Analysis;SQL,3,75.26,9,0
1,2,Java,4,74.25,6,2
2,3,Data Analysis,2,74.89,4,3
3,4,Data Analysis,4,72.73,2,3
4,5,Machine Learning;Python;C++,4,84.85,1,4
...,...,...,...,...,...,...
19995,19996,Python,1,62.54,1,2
19996,19997,Python;Machine Learning,2,84.13,2,2
19997,19998,Data Analysis;Java;Machine Learning,1,83.76,7,2
19998,19999,SQL;Python,2,60.50,2,3
19999,20000,Machine Learning,1,73.69,9,3

In [28]:
y=data['job_offer']

In [29]:
y.size

20000

In [30]:
y

0        1
1        1
2        0
3        1
4        0
        ..
19995    1
19996    1
19997    1
19998    1
19999    1
Name: job_offer, Length: 20000, dtype: int64

In [31]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x['skills']=le.fit_transform(x['skills'])
x['extracurriculars']=le.fit_transform(x['extracurriculars'])
x

<ipython-input-31-ca50673b6b43>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['skills']=le.fit_transform(x['skills'])
<ipython-input-31-ca50673b6b43>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['extracurriculars']=le.fit_transform(x['extracurriculars'])

,student_id,skills,experience_years,course_grades,projects_completed,extracurriculars
0,1,114,3,75.26,9,0
1,2,52,4,74.25,6,2
2,3,26,2,74.89,4,3
3,4,26,4,72.73,2,3
4,5,95,4,84.85,1,4
...,...,...,...,...,...,...
19995,19996,104,1,62.54,1,2
19996,19997,120,2,84.13,2,2
19997,19998,34,1,83.76,7,2
19998,19999,151,2,60.50,2,3
19999,20000,78,1,73.69,9,3

In [32]:
from sklearn.preprocessing import StandardScaler,LabelEncoder
scaler=StandardScaler()
x_scaled=scaler.fit_transform(x)
x_scaled

array([[-1.73196421,  0.92416416,  0.29278387, -0.41954351,  1.56462467,
        -1.41301399],
       [-1.731791  , -0.4463499 ,  0.87729949, -0.50721996,  0.51574944,
         0.00205185],
       [-1.7316178 , -1.02108161, -0.29173174, -0.45166261, -0.18350072,
         0.70958476],
       ...,
       [ 1.7316178 , -0.84424108, -0.87624736,  0.31832757,  0.86537451,
         0.00205185],
       [ 1.731791  ,  1.74205158, -0.29173174, -1.70083494, -0.88275088,
         0.70958476],
       [ 1.73196421,  0.1283818 , -0.87624736, -0.55583264,  1.56462467,
         0.70958476]])

In [33]:
from keras.utils import to_categorical
y_encoded=to_categorical(y)
x_train,x_test,y_train,y_test=train_test_split(x_scaled,y_encoded,test_size=0.2)
x_train.shape

(16000, 6)

In [34]:
model=Sequential()
model.add(Dense(32,input_shape=(x_train.shape[1],),activation='relu'))
model.add(Dense(2,activation='softmax'))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [35]:
model.compile(optimizer='Adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [36]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                      │ (None, 32)                  │             224 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 2)                   │              66 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 290 (1.13 KB)

 Trainable params: 290 (1.13 KB)

 Non-trainable params: 0 (0.00 B)

In [37]:
model.compile(optimizer='Adam',loss='categorical_crossentropy',metrics=['accuracy'])
model.fit(x_train,y_train,epochs=5)

Epoch 1/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.5021 - loss: 0.7085
Epoch 2/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5069 - loss: 0.6942
Epoch 3/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5155 - loss: 0.6936
Epoch 4/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5147 - loss: 0.6934
Epoch 5/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5175 - loss: 0.6928

In [38]:
model.compile(optimizer='Adam',loss='categorical_crossentropy',metrics=['accuracy'])
loss,accuracy=model.evaluate(x_test,y_test)

125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5078 - loss: 0.6952

In [39]:
print('loss:',loss)
print('accuracy:',accuracy)

loss: 0.6951786875724792
accuracy: 0.5052499771118164